version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment: 
       MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3307:3307