version: "3.9"
services:
  db:
    container_name: db
    build:
      context: ./docker_db
    restart: always
#    volumes:
#      - ./db_data:/var/lib/mysql
    environment: 
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: stockbot
       MYSQL_USER: tendies
       MYSQL_PASSWORD: tendies
    ports: 
      - 3306:3306
    # Required for weird characters
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']